name: CD

on:
  workflow_run: 
    workflows: ["CI"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-lastest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        branch: main
        folder: build