name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git identity
        run: |
          git config --global user.email "BadGuitarist07@gmail.com"
          git config --global user.name "BadGuitarist07"

      - name: Configure Git credentials
        run: echo "//github.com/${{ github.repository }}.git//?ref=${{ github.sha }}" > $HOME/.git-credentials
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy to GitHub Pages
        run: gh-pages -d build -e $HOME/.git-credentials
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
